### ISSUE TITLE
Why do we need to add `__typename` to each data

### ISSUE THREAD

**Issue by scottming** [DivvyPayHQ/absinthe_federation#33]
We always need to put a `__typename` to the result, I don't think this is a good way to write the `_resolve_reference` function

https://github.com/scottming/federation_poc/blob/master/products/lib/products_web/schema.ex#L70

In reality, we don't write code like [this](https://github.com/DivvyPayHQ/absinthe_federation/blob/e1371bc2776e6cb64ed17f3ac6ec3d9b63e627d8/test/absinthe/federation/schema/entities_field_test.exs#L61), this args is `%{upc: upc, __typename: "Product"}`.

normally, we should just extract the key from `args`, and do some resolve logic, and return.

**Comment by kdawgwilk** [comment]
you don't have to define a `__typename` in the `_resolve_reference` if your `_resolve_reference` returns a ecto schema struct that will work as well.  We are not super happy with the ergonomics of this which is why we have #11 open for us to look into.  Also a bit of work was done to look into this in #20

**Comment by kdawgwilk** [comment]
Sorry link to the wrong PR but this PR added the protocol to resolve struct types https://github.com/DivvyPayHQ/absinthe_federation/pull/26
